SELECT DISTINCT DEPTNO, JOB FROM EMP;

SELECT EMPNO 사원번호, ENAME 사원이름, SAL 급여, SAL * 12 연봉 FROM EMP;

SELECT 10 * 10 FROM DUAL;

SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL DESC, EMPNO DESC; 

SELECT * FROM EMP WHERE SAL >= 1500 AND SAL < 3000 ORDER BY SAL;

SELECT * FROM EMP WHERE SAL < 1500 OR SAL >= 3000 ORDER BY SAL;

SELECT * FROM EMP WHERE NOT(SAL >= 1500 AND SAL < 3000) ORDER BY SAL;

SELECT * FROM EMP WHERE JOB = 'SALESMAN' 
OR (JOB = 'MANAGER' AND SAL > 2500);

SELECT * FROM EMP 
WHERE JOB = 'SALESMAN' OR JOB = 'MANAGER' OR JOB = 'CLERK';

SELECT * FROM EMP WHERE JOB IN ('SALESMAN', 'MANAGER', 'CLERK');

SELECT * FROM EMP WHERE JOB NOT IN ('SALESMAN', 'MANAGER', 'CLERK');

SELECT * FROM EMP 
WHERE HIREDATE >= TO_DATE('1981-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') 
AND HIREDATE <= TO_DATE('1981-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

SELECT * FROM EMP
WHERE HIREDATE BETWEEN TO_DATE('1981-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') 
AND TO_DATE('1981-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

SELECT * FROM EMP;
SELECT * FROM EMP WHERE JOB LIKE 'SALESMAN';
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE 'S%' AND ENAME LIKE '%H';
SELECT * FROM EMP WHERE ENAME LIKE '%N%';

SELECT * FROM EMP WHERE ENAME LIKE '__A%';

SELECT NULL + 100 FROM DUAL;

SELECT EMPNO, ENAME, SAL, SAL * 12 + NVL() COMM 연봉 FROM EMP;









